package com.ssajudn.hushkeep.core.config

import com.ssajudn.hushkeep.BuildConfig

/**
 * Build-time values generated by the Gradle configuration.
 *
 * The Supabase anon key is intentionally a client value. Service-role keys must
 * never be placed in this class or shipped in the Android application.
 */
object BuildConfigFields {
    val supabaseUrl: String
        get() = BuildConfig.SUPABASE_URL

    val supabaseAnonKey: String
        get() = BuildConfig.SUPABASE_ANON_KEY

    val environment: String
        get() = BuildConfig.APP_ENVIRONMENT
}
